name: .NET Latest

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix: # https://stackoverflow.com/a/68940067/16608030 hopefully this still works
        dotnet: [ {version: '5.0.x', path: net5.0}, {version: '6.0.x', path: net6.0} ]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT : true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet.version }}
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish (ConverterApp)
      run: dotnet publish -c Release -r win-x64 -P:PublishSingleFile=true -p:PublishTrimmed=false --self-contained false -p:TargetFramwork=${{matrix.dotnet.path}}-windows ConverterApp
    - name: Upload artifact (ConverterApp
      uses: actions/upload-artifact@v2
      with:
        name: ConverterApp
        path: ConverterApp\bin\Release\${{ matrix.dotnet.path}}-windows\win-x64\publish\
    - name: Publish (Divine)
      run: dotnet publish -c Release -r win-x64 -P:PublishSingleFile=true -p:PublishTrimmed=false --self-contained false -p:TargetFramwork=${{matrix.dotnet.path}} Divine
    - name: Upload artifact (Divine
      uses: actions/upload-artifact@v2
      with:
        name: Divine
        path: Divine\bin\Release\${{matrix.dotnet.path}}\win-x64\publish\
        
        